MASON = "application/vnd.mason+json"
LINK_RELATIONS_URL = "/plandi/link-relations/"
ERROR_PROFILE = "/profiles/error/"
DIARY_PROFILE = "/profiles/diary/"
PLANT_ITEM_PROFILE = "/profiles/plant_item/"
PLANT_COLLECTION_PROFILE = "/profiles/plant_collection/"
SPECIE_PROFILE = "/profiles/specie/"
